# definition functions
from typing import TypeVar


Number = TypeVar("Number", int, float)


def m_to_cm(values: Number) -> Number: ...
def cm_to_m(values: Number) -> Number: ...
def cm_to_mm(values: Number) -> Number: ...
def mm_to_cm(values: Number) -> Number: ...
def m_to_mm(values: Number) -> Number: ...
def mm_to_m(values: Number) -> Number: ...
